# Generated by sitemills-cli-internal/scripts/release-public.mjs. Do not edit by hand.
class SitemillsCli < Formula
  desc "Build, deploy, and manage SiteMills apps from the command-line"
  homepage "https://github.com/SiteMills/sitemills-cli"
  version "1.0.8"

  on_macos do
    on_intel do
      url "https://github.com/SiteMills/sitemills-cli/releases/download/v1.0.8/sitemills-macos"
      sha256 "237ac7e8649c793d9eb6a260ea41e07835452b59b720d54c392cddf1b4fd953a"
    end
    on_arm do
      url "https://github.com/SiteMills/sitemills-cli/releases/download/v1.0.8/sitemills-macos-arm64"
      sha256 "91430d0d53480c79abb2bdcc52975bd06822a79001690909aa5efc4d30420d13"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/SiteMills/sitemills-cli/releases/download/v1.0.8/sitemills-linux"
      sha256 "81aa868a7c4b340a6f2a400a9173ad492d93371e157349cf970d89a9e4d86930"
    end
  end

  def install
    bin.install Dir["sitemills-*"].first => "sitemills-cli"
  end

  test do
    assert_match "sitemills-cli v#{version}", shell_output("#{bin}/sitemills-cli version --no-update")
  end
end
