# Generated by sitemills-cli-internal/scripts/release-public.mjs. Do not edit by hand.
class SitemillsCli < Formula
  desc "Build, deploy, and manage SiteMills apps from the command-line"
  homepage "https://github.com/SiteMills/sitemills-cli"
  version "1.0.2"

  on_macos do
    # One x86_64 build; Apple Silicon runs it under Rosetta 2.
    on_intel do
      url "https://github.com/SiteMills/sitemills-cli/releases/download/v1.0.2/sitemills-macos"
      sha256 "4234b3ae35fcae02e5f91370c38974966a021bcf9cd0706eede2a06e432ebb42"
    end
    on_arm do
      url "https://github.com/SiteMills/sitemills-cli/releases/download/v1.0.2/sitemills-macos"
      sha256 "4234b3ae35fcae02e5f91370c38974966a021bcf9cd0706eede2a06e432ebb42"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/SiteMills/sitemills-cli/releases/download/v1.0.2/sitemills-linux"
      sha256 "13f7cacfe6d0c3ce4f59847052fc34203b14aacb24afdc23946a1598361b8e28"
    end
  end

  def install
    bin.install (OS.mac? ? "sitemills-macos" : "sitemills-linux") => "sitemills-cli"
  end

  def caveats
    on_macos do
      on_arm do
        <<~EOS
          This build runs under Rosetta 2 on Apple Silicon. If it is not installed:
            softwareupdate --install-rosetta --agree-to-license
        EOS
      end
    end
  end

  test do
    assert_match "sitemills-cli v#{version}", shell_output("#{bin}/sitemills-cli version --no-update")
  end
end
